dist: xenial 
sudo: required
language: java
os: linux
arch:
  - amd64
  - ppc64le
jdk: openjdk11
script: mvn install -DskipTests
addons:
  apt:
  packages:
    - maven
services:
- docker
before_install:
- gem install asciidoctor
script:
- "./.travis/build.sh"
